### ISSUE TITLE
Update CODEOWNERS to individual owners

### ISSUE THREAD

**Issue by peternied** [opensearch-project/traffic-replayer#9]
- Following the guidance from https://github.com/opensearch-project/.github/issues/125

https://github.com/opensearch-project/traffic-replayer/blob/9e952925ee6b3c9d22d30aa84d10c261590addd1/.github/CODEOWNERS#L1-L2

This should be a list of all the maintainers of this project instead of a team.

**Comment by peternied** [comment]
@wbeckler It looks like you are listed as a maintainer on this project per the Manage access screen and not listed on the maintainers.md file.

**Comment by dblock** [comment]
Done in #10.
